import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { verifyComposition } from "../verify-colorstack-composition.mjs";

const run = (cwd, ...args) => execFileSync("git", ["-C", cwd, ...args], { encoding: "utf8" }).trim();
const source = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../config/colorstack");
const outputs = ["ghostty-theme", "tmux-include", "bat-theme", "shell-env", "starship-select", "starship-palette", "herdr", "pi-theme", "jupyter-css", "jupyter-cfg", "jupyter-theme"];
function fixture() {
  const root = mkdtempSync(path.join(process.cwd(), ".colorstack-composition-test-")), child = path.join(root, "config/colorstack");
  mkdirSync(path.dirname(child), { recursive: true }); cpSync(source, child, { recursive: true, filter: (entry) => path.basename(entry) !== ".git" });
  for (const repo of [root, child]) { run(repo, "init", "-q"); run(repo, "config", "user.email", "privacy-fixture@example.invalid"); run(repo, "config", "user.name", "Test"); }
  run(child, "remote", "add", "origin", "https://github.com/deephbz/colorstack.git"); run(child, "add", "."); run(child, "commit", "-qm", "child");
  const commit = run(child, "rev-parse", "HEAD"), tree = run(child, "rev-parse", "HEAD^{tree}"); run(root, "update-index", "--add", "--cacheinfo", `160000,${commit},config/colorstack`); run(root, "commit", "-qm", "root");
  mkdirSync(path.join(root, "config/schemas"), { recursive: true });
  const record = { schemaVersion: 1, component: "colorstack", source: { repository: "https://github.com/deephbz/colorstack.git", commit, tree }, gitlink: { path: "config/colorstack", mode: "160000", commit }, pythonProject: { name: "colorstack", version: "0.1.0", requiresPython: ">=3.11" }, generator: { path: "gen.py", manifest: ".colorstack-manifest.json", manifestSchemaVersion: 1 }, coreOutputs: ["ghostty-theme", "herdr"], parentVerification: { state: "verified", verifier: "scripts/verify-colorstack-composition.mjs", requiredCheckout: "recursive" } };
  const selection = { schemaVersion: 1, scheme: "modus", inkContrast: 10, outputs };
  writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); writeFileSync(path.join(root, "config/colorstack-selection.json"), JSON.stringify(selection));
  for (const name of ["colorstack-compatibility.schema.json", "colorstack-selection.schema.json"]) writeFileSync(path.join(root, "config/schemas", name), JSON.stringify({ $schema: "http://json-schema.org/draft-07/schema#", type: "object" }));
  return { root, child, record, selection, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}
async function state(name, mutate, code) { await test(name, () => { const f = fixture(); try { mutate(f); assert.throws(() => verifyComposition({ root: f.root }), (error) => error.code === code); } finally { f.cleanup(); } }); }
test("verifies a clean Colorstack source and exact selection through a removed OS temp bundle", () => { const f = fixture(); try { const result = verifyComposition({ root: f.root, debug: true }); assert.equal(result.record.component, "colorstack"); assert.ok(!result.trace.outputRoot.startsWith(f.root)); assert.equal(existsSync(result.trace.outputRoot), false); } finally { f.cleanup(); } });
test("CLI default is compact verified JSON while debug carries record, selection, and trace", () => { const script = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../verify-colorstack-composition.mjs"); const plain = execFileSync(process.execPath, [script], { encoding: "utf8" }); const debug = execFileSync(process.execPath, [script, "--debug"], { encoding: "utf8" }); assert.deepEqual(JSON.parse(plain), { component: "colorstack", revision: "c0a1a51bef009a2e549391e3c5835fd2e4960dcc", status: "verified" }); assert.doesNotMatch(plain, /\n  /); const traced = JSON.parse(debug); assert.ok(traced.record && traced.selection && traced.trace); });
await state("distinguishes missing and uninitialized source", ({ root }) => rmSync(path.join(root, "config/colorstack"), { recursive: true }), "missing-submodule");
await state("distinguishes uninitialized source", ({ child }) => rmSync(path.join(child, ".git"), { recursive: true }), "uninitialized-submodule");
await state("distinguishes dirty source", ({ child }) => writeFileSync(path.join(child, "dirty"), "x"), "dirty-submodule");
await state("distinguishes wrong origin", ({ child }) => run(child, "remote", "set-url", "origin", "https://example.test/wrong.git"), "origin");
await state("distinguishes wrong revision and tree", ({ child }) => { writeFileSync(path.join(child, "next"), "x"); run(child, "add", "."); run(child, "commit", "-qm", "next"); }, "revision");
await state("distinguishes wrong tree", ({ root, record }) => { record.source.tree = "0".repeat(40); writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); }, "tree");
await state("distinguishes Python project identity and range drift", ({ child, root, record }) => { const file = path.join(child, "pyproject.toml"); writeFileSync(file, readFileSync(file, "utf8").replace('requires-python = ">=3.11"', 'requires-python = ">=3.12"')); run(child, "add", "."); run(child, "commit", "-qm", "range"); const commit = run(child, "rev-parse", "HEAD"); record.source.commit = record.gitlink.commit = commit; record.source.tree = run(child, "rev-parse", "HEAD^{tree}"); run(root, "update-index", "--cacheinfo", `160000,${commit},config/colorstack`); writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); }, "requires-python");
await state("distinguishes Python project identity drift", ({ child, root, record }) => { const file = path.join(child, "pyproject.toml"); writeFileSync(file, readFileSync(file, "utf8").replace('name = "colorstack"', 'name = "wrong"')); run(child, "add", "."); run(child, "commit", "-qm", "name"); const commit = run(child, "rev-parse", "HEAD"); record.source.commit = record.gitlink.commit = commit; record.source.tree = run(child, "rev-parse", "HEAD^{tree}"); run(root, "update-index", "--cacheinfo", `160000,${commit},config/colorstack`); writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); }, "python-name");
await state("rejects unsupported scheme and output", ({ root, selection }) => { selection.scheme = "other"; writeFileSync(path.join(root, "config/colorstack-selection.json"), JSON.stringify(selection)); }, "invalid-selection");
await state("rejects unsupported selection output", ({ root, selection }) => { selection.outputs = [...selection.outputs, "css"]; writeFileSync(path.join(root, "config/colorstack-selection.json"), JSON.stringify(selection)); }, "invalid-selection");
await state("rejects a missing selected output", ({ child, root, record }) => { const file = path.join(child, "gen.py"); writeFileSync(file, readFileSync(file, "utf8").replace("return {key: EMITTERS[key](th) for key in keys}", "return {key: EMITTERS[key](th) for key in keys if key != 'jupyter-theme'}")); run(child, "add", "."); run(child, "commit", "-qm", "missing output"); const commit = run(child, "rev-parse", "HEAD"); record.source.commit = record.gitlink.commit = commit; record.source.tree = run(child, "rev-parse", "HEAD^{tree}"); run(root, "update-index", "--cacheinfo", `160000,${commit},config/colorstack`); writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); }, "output");
await state("detects generator and manifest drift", ({ child, root, record }) => { writeFileSync(path.join(child, "gen.py"), readFileSync(path.join(child, "gen.py"), "utf8").replace('"schema_version": 1', '"schema_version": 2')); run(child, "add", "."); run(child, "commit", "-qm", "manifest drift"); const commit = run(child, "rev-parse", "HEAD"); record.source.commit = record.gitlink.commit = commit; record.source.tree = run(child, "rev-parse", "HEAD^{tree}"); run(root, "update-index", "--cacheinfo", `160000,${commit},config/colorstack`); writeFileSync(path.join(root, "config/colorstack-compatibility.json"), JSON.stringify(record)); }, "manifest-schema");
